routes:
  /:
    template: godo-home-personal
    data: page.home-personal
collections:
  # Default
  /articles/:
    permalink: /articles/{slug}/
    filter: 'tag:-[hash-bytes,hash-liam]'
    template: index
  /bytes/:
    permalink: /bytes/{slug}/
    filter: 'tag:[hash-bytes]'
    template: godo-template-grid
  /liam/:
    permalink: /liam/{slug}/
    filter: 'tag:[hash-liam]'
    template: godo-template-grid
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/